server:
  address: ${SERVE_ADDR:127.0.0.1:5000}

cache:
  interval: 30
  duration: second

redis:
  address: "127.0.0.1:6379"

postgres:
  db_name: "referral db name"
  user: "your_user"
  password: "password"
