// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: referral/referral.proto

package referral

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateReferralLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReferralLinkRequest) Reset() {
	*x = GenerateReferralLinkRequest{}
	mi := &file_referral_referral_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReferralLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReferralLinkRequest) ProtoMessage() {}

func (x *GenerateReferralLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReferralLinkRequest.ProtoReflect.Descriptor instead.
func (*GenerateReferralLinkRequest) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateReferralLinkRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GenerateReferralLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReferralLinkResponse) Reset() {
	*x = GenerateReferralLinkResponse{}
	mi := &file_referral_referral_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReferralLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReferralLinkResponse) ProtoMessage() {}

func (x *GenerateReferralLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReferralLinkResponse.ProtoReflect.Descriptor instead.
func (*GenerateReferralLinkResponse) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateReferralLinkResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ReferralLinkWrapper struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Referrallink  *GenerateReferralLinkRequest `protobuf:"bytes,1,opt,name=referrallink,proto3" json:"referrallink,omitempty"` // Field used as HTTP POST body
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferralLinkWrapper) Reset() {
	*x = ReferralLinkWrapper{}
	mi := &file_referral_referral_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferralLinkWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferralLinkWrapper) ProtoMessage() {}

func (x *ReferralLinkWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferralLinkWrapper.ProtoReflect.Descriptor instead.
func (*ReferralLinkWrapper) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{2}
}

func (x *ReferralLinkWrapper) GetReferrallink() *GenerateReferralLinkRequest {
	if x != nil {
		return x.Referrallink
	}
	return nil
}

type Program struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Createdat     int64                  `protobuf:"varint,5,opt,name=createdat,proto3" json:"createdat,omitempty"`
	Updatedat     int64                  `protobuf:"varint,6,opt,name=updatedat,proto3" json:"updatedat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Program) Reset() {
	*x = Program{}
	mi := &file_referral_referral_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{3}
}

func (x *Program) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Program) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Program) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Program) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Program) GetCreatedat() int64 {
	if x != nil {
		return x.Createdat
	}
	return 0
}

func (x *Program) GetUpdatedat() int64 {
	if x != nil {
		return x.Updatedat
	}
	return 0
}

type AddProgramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProgramRequest) Reset() {
	*x = AddProgramRequest{}
	mi := &file_referral_referral_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProgramRequest) ProtoMessage() {}

func (x *AddProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProgramRequest.ProtoReflect.Descriptor instead.
func (*AddProgramRequest) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{4}
}

func (x *AddProgramRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProgramRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddProgramRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type AddProgramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProgramResponse) Reset() {
	*x = AddProgramResponse{}
	mi := &file_referral_referral_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProgramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProgramResponse) ProtoMessage() {}

func (x *AddProgramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProgramResponse.ProtoReflect.Descriptor instead.
func (*AddProgramResponse) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{5}
}

func (x *AddProgramResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateProgramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Active        *bool                  `protobuf:"varint,4,opt,name=active,proto3,oneof" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgramRequest) Reset() {
	*x = UpdateProgramRequest{}
	mi := &file_referral_referral_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgramRequest) ProtoMessage() {}

func (x *UpdateProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgramRequest.ProtoReflect.Descriptor instead.
func (*UpdateProgramRequest) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProgramRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProgramRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProgramRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateProgramRequest) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

type UpdagteProgramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Program       *Program               `protobuf:"bytes,1,opt,name=program,proto3" json:"program,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdagteProgramResponse) Reset() {
	*x = UpdagteProgramResponse{}
	mi := &file_referral_referral_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdagteProgramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdagteProgramResponse) ProtoMessage() {}

func (x *UpdagteProgramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdagteProgramResponse.ProtoReflect.Descriptor instead.
func (*UpdagteProgramResponse) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{7}
}

func (x *UpdagteProgramResponse) GetProgram() *Program {
	if x != nil {
		return x.Program
	}
	return nil
}

type GetProgramsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int64                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Size          *int64                 `protobuf:"varint,2,opt,name=size,proto3,oneof" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramsRequest) Reset() {
	*x = GetProgramsRequest{}
	mi := &file_referral_referral_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramsRequest) ProtoMessage() {}

func (x *GetProgramsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramsRequest.ProtoReflect.Descriptor instead.
func (*GetProgramsRequest) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{8}
}

func (x *GetProgramsRequest) GetPage() int64 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *GetProgramsRequest) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type GetProgramsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Programs      []*Program             `protobuf:"bytes,1,rep,name=programs,proto3" json:"programs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramsResponse) Reset() {
	*x = GetProgramsResponse{}
	mi := &file_referral_referral_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramsResponse) ProtoMessage() {}

func (x *GetProgramsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramsResponse.ProtoReflect.Descriptor instead.
func (*GetProgramsResponse) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{9}
}

func (x *GetProgramsResponse) GetPrograms() []*Program {
	if x != nil {
		return x.Programs
	}
	return nil
}

type GetProgramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramRequest) Reset() {
	*x = GetProgramRequest{}
	mi := &file_referral_referral_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramRequest) ProtoMessage() {}

func (x *GetProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramRequest.ProtoReflect.Descriptor instead.
func (*GetProgramRequest) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{10}
}

func (x *GetProgramRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProgramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Program       *Program               `protobuf:"bytes,1,opt,name=program,proto3" json:"program,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramResponse) Reset() {
	*x = GetProgramResponse{}
	mi := &file_referral_referral_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramResponse) ProtoMessage() {}

func (x *GetProgramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramResponse.ProtoReflect.Descriptor instead.
func (*GetProgramResponse) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{11}
}

func (x *GetProgramResponse) GetProgram() *Program {
	if x != nil {
		return x.Program
	}
	return nil
}

// member
type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	ProgramId     string                 `protobuf:"bytes,5,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	ReferralCode  string                 `protobuf:"bytes,6,opt,name=referral_code,json=referralCode,proto3" json:"referral_code,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_referral_referral_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{12}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Member) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Member) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Member) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *Member) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

func (x *Member) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Member) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Member) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int64                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Size          *int64                 `protobuf:"varint,2,opt,name=size,proto3,oneof" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersRequest) Reset() {
	*x = GetMembersRequest{}
	mi := &file_referral_referral_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersRequest) ProtoMessage() {}

func (x *GetMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersRequest.ProtoReflect.Descriptor instead.
func (*GetMembersRequest) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{13}
}

func (x *GetMembersRequest) GetPage() int64 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *GetMembersRequest) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type GetMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersResponse) Reset() {
	*x = GetMembersResponse{}
	mi := &file_referral_referral_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersResponse) ProtoMessage() {}

func (x *GetMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersResponse.ProtoReflect.Descriptor instead.
func (*GetMembersResponse) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{14}
}

func (x *GetMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ReferralCode  *string                `protobuf:"bytes,4,opt,name=referral_code,json=referralCode,proto3,oneof" json:"referral_code,omitempty"`
	ProgramId     string                 `protobuf:"bytes,5,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	IsActive      *bool                  `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_referral_referral_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{15}
}

func (x *AddMemberRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AddMemberRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *AddMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddMemberRequest) GetReferralCode() string {
	if x != nil && x.ReferralCode != nil {
		return *x.ReferralCode
	}
	return ""
}

func (x *AddMemberRequest) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *AddMemberRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_referral_referral_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{16}
}

func (x *AddMemberResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// referral
type Referral struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName         string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName          string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email             string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone             string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	ReferralCode      string                 `protobuf:"bytes,6,opt,name=referral_code,json=referralCode,proto3" json:"referral_code,omitempty"`
	ProgramId         string                 `protobuf:"bytes,7,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	ReferringMemberId string                 `protobuf:"bytes,8,opt,name=referring_member_id,json=referringMemberId,proto3" json:"referring_member_id,omitempty"`
	Status            string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Referral) Reset() {
	*x = Referral{}
	mi := &file_referral_referral_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Referral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Referral) ProtoMessage() {}

func (x *Referral) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Referral.ProtoReflect.Descriptor instead.
func (*Referral) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{17}
}

func (x *Referral) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Referral) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Referral) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Referral) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Referral) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Referral) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

func (x *Referral) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *Referral) GetReferringMemberId() string {
	if x != nil {
		return x.ReferringMemberId
	}
	return ""
}

func (x *Referral) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Referral) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Referral) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AddReferralRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     *string                `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Email         *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	ReferralCode  string                 `protobuf:"bytes,5,opt,name=referral_code,json=referralCode,proto3" json:"referral_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReferralRequest) Reset() {
	*x = AddReferralRequest{}
	mi := &file_referral_referral_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReferralRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReferralRequest) ProtoMessage() {}

func (x *AddReferralRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReferralRequest.ProtoReflect.Descriptor instead.
func (*AddReferralRequest) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{18}
}

func (x *AddReferralRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *AddReferralRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *AddReferralRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *AddReferralRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *AddReferralRequest) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

type AddReferralResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReferralResponse) Reset() {
	*x = AddReferralResponse{}
	mi := &file_referral_referral_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReferralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReferralResponse) ProtoMessage() {}

func (x *AddReferralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReferralResponse.ProtoReflect.Descriptor instead.
func (*AddReferralResponse) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{19}
}

func (x *AddReferralResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReferralsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int64                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Size          *int64                 `protobuf:"varint,2,opt,name=size,proto3,oneof" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferralsRequest) Reset() {
	*x = GetReferralsRequest{}
	mi := &file_referral_referral_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferralsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferralsRequest) ProtoMessage() {}

func (x *GetReferralsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferralsRequest.ProtoReflect.Descriptor instead.
func (*GetReferralsRequest) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{20}
}

func (x *GetReferralsRequest) GetPage() int64 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *GetReferralsRequest) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type GetReferralsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Referrals     []*Referral            `protobuf:"bytes,1,rep,name=referrals,proto3" json:"referrals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferralsResponse) Reset() {
	*x = GetReferralsResponse{}
	mi := &file_referral_referral_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferralsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferralsResponse) ProtoMessage() {}

func (x *GetReferralsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_referral_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferralsResponse.ProtoReflect.Descriptor instead.
func (*GetReferralsResponse) Descriptor() ([]byte, []int) {
	return file_referral_referral_proto_rawDescGZIP(), []int{21}
}

func (x *GetReferralsResponse) GetReferrals() []*Referral {
	if x != nil {
		return x.Referrals
	}
	return nil
}

var File_referral_referral_proto protoreflect.FileDescriptor

const file_referral_referral_proto_rawDesc = "" +
	"\n" +
	"\x17referral/referral.proto\x12\breferral\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"3\n" +
	"\x1bGenerateReferralLinkRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"0\n" +
	"\x1cGenerateReferralLinkResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"`\n" +
	"\x13ReferralLinkWrapper\x12I\n" +
	"\freferrallink\x18\x01 \x01(\v2%.referral.GenerateReferralLinkRequestR\freferrallink\"\x97\x01\n" +
	"\aProgram\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12\x1c\n" +
	"\tcreatedat\x18\x05 \x01(\x03R\tcreatedat\x12\x1c\n" +
	"\tupdatedat\x18\x06 \x01(\x03R\tupdatedat\"U\n" +
	"\x11AddProgramRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\"$\n" +
	"\x12AddProgramResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x95\x01\n" +
	"\x14UpdateProgramRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x01R\x05title\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x04 \x01(\bH\x02R\x06active\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_titleB\t\n" +
	"\a_active\"E\n" +
	"\x16UpdagteProgramResponse\x12+\n" +
	"\aprogram\x18\x01 \x01(\v2\x11.referral.ProgramR\aprogram\"X\n" +
	"\x12GetProgramsRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x03H\x00R\x04page\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x02 \x01(\x03H\x01R\x04size\x88\x01\x01B\a\n" +
	"\x05_pageB\a\n" +
	"\x05_size\"D\n" +
	"\x13GetProgramsResponse\x12-\n" +
	"\bprograms\x18\x01 \x03(\v2\x11.referral.ProgramR\bprograms\"#\n" +
	"\x11GetProgramRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x12GetProgramResponse\x12+\n" +
	"\aprogram\x18\x01 \x01(\v2\x11.referral.ProgramR\aprogram\"\x89\x02\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"program_id\x18\x05 \x01(\tR\tprogramId\x12#\n" +
	"\rreferral_code\x18\x06 \x01(\tR\freferralCode\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"W\n" +
	"\x11GetMembersRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x03H\x00R\x04page\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x02 \x01(\x03H\x01R\x04size\x88\x01\x01B\a\n" +
	"\x05_pageB\a\n" +
	"\x05_size\"@\n" +
	"\x12GetMembersResponse\x12*\n" +
	"\amembers\x18\x01 \x03(\v2\x10.referral.MemberR\amembers\"\x82\x02\n" +
	"\x10AddMemberRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12 \n" +
	"\tlast_name\x18\x02 \x01(\tH\x00R\blastName\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12(\n" +
	"\rreferral_code\x18\x04 \x01(\tH\x01R\freferralCode\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"program_id\x18\x05 \x01(\tR\tprogramId\x12 \n" +
	"\tis_active\x18\x06 \x01(\bH\x02R\bisActive\x88\x01\x01B\f\n" +
	"\n" +
	"_last_nameB\x10\n" +
	"\x0e_referral_codeB\f\n" +
	"\n" +
	"_is_active\"#\n" +
	"\x11AddMemberResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xcc\x02\n" +
	"\bReferral\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12#\n" +
	"\rreferral_code\x18\x06 \x01(\tR\freferralCode\x12\x1d\n" +
	"\n" +
	"program_id\x18\a \x01(\tR\tprogramId\x12.\n" +
	"\x13referring_member_id\x18\b \x01(\tR\x11referringMemberId\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"\xe6\x01\n" +
	"\x12AddReferralRequest\x12\"\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x02 \x01(\tH\x01R\blastName\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x02R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x03R\x05phone\x88\x01\x01\x12#\n" +
	"\rreferral_code\x18\x05 \x01(\tR\freferralCodeB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phone\"%\n" +
	"\x13AddReferralResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x13GetReferralsRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x03H\x00R\x04page\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x02 \x01(\x03H\x01R\x04size\x88\x01\x01B\a\n" +
	"\x05_pageB\a\n" +
	"\x05_size\"H\n" +
	"\x14GetReferralsResponse\x120\n" +
	"\treferrals\x18\x01 \x03(\v2\x12.referral.ReferralR\treferrals2\xd7\x06\n" +
	"\x10referral_service\x12d\n" +
	"\vGetPrograms\x12\x1c.referral.GetProgramsRequest\x1a\x1d.referral.GetProgramsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/programs\x12o\n" +
	"\n" +
	"GetProgram\x12\x1b.referral.GetProgramRequest\x1a\x1c.referral.GetProgramResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/v1/programs/singleProgram\x12d\n" +
	"\n" +
	"AddProgram\x12\x1b.referral.AddProgramRequest\x1a\x1c.referral.AddProgramResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/programs\x12n\n" +
	"\rUpdateProgram\x12\x1e.referral.UpdateProgramRequest\x1a .referral.UpdagteProgramResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/api/v1/programs\x12`\n" +
	"\n" +
	"GetMembers\x12\x1b.referral.GetMembersRequest\x1a\x1c.referral.GetMembersResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/members\x12`\n" +
	"\tAddMember\x12\x1a.referral.AddMemberRequest\x1a\x1b.referral.AddMemberResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/members\x12h\n" +
	"\fGetReferrals\x12\x1d.referral.GetReferralsRequest\x1a\x1e.referral.GetReferralsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/referrals\x12h\n" +
	"\vAddReferral\x12\x1c.referral.AddReferralRequest\x1a\x1d.referral.AddReferralResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/referralsB\xfc\x01\x92A\xd7\x01\x12q\n" +
	"\x0fReferralService\x12#Referral Service openapi definition\"4\n" +
	"\x0egrpc-with-rest\x12\"https://github.com/ReferralService2\x031.0*\x01\x022\x10application/json:\x10application/jsonR;\n" +
	"\x03404\x124\n" +
	"*Returned when the resource does not exist.\x12\x06\n" +
	"\x04\x9a\x02\x01\aZ\x1freferral-service/proto/referralb\x06proto3"

var (
	file_referral_referral_proto_rawDescOnce sync.Once
	file_referral_referral_proto_rawDescData []byte
)

func file_referral_referral_proto_rawDescGZIP() []byte {
	file_referral_referral_proto_rawDescOnce.Do(func() {
		file_referral_referral_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_referral_referral_proto_rawDesc), len(file_referral_referral_proto_rawDesc)))
	})
	return file_referral_referral_proto_rawDescData
}

var file_referral_referral_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_referral_referral_proto_goTypes = []any{
	(*GenerateReferralLinkRequest)(nil),  // 0: referral.GenerateReferralLinkRequest
	(*GenerateReferralLinkResponse)(nil), // 1: referral.GenerateReferralLinkResponse
	(*ReferralLinkWrapper)(nil),          // 2: referral.ReferralLinkWrapper
	(*Program)(nil),                      // 3: referral.Program
	(*AddProgramRequest)(nil),            // 4: referral.AddProgramRequest
	(*AddProgramResponse)(nil),           // 5: referral.AddProgramResponse
	(*UpdateProgramRequest)(nil),         // 6: referral.UpdateProgramRequest
	(*UpdagteProgramResponse)(nil),       // 7: referral.UpdagteProgramResponse
	(*GetProgramsRequest)(nil),           // 8: referral.GetProgramsRequest
	(*GetProgramsResponse)(nil),          // 9: referral.GetProgramsResponse
	(*GetProgramRequest)(nil),            // 10: referral.GetProgramRequest
	(*GetProgramResponse)(nil),           // 11: referral.GetProgramResponse
	(*Member)(nil),                       // 12: referral.Member
	(*GetMembersRequest)(nil),            // 13: referral.GetMembersRequest
	(*GetMembersResponse)(nil),           // 14: referral.GetMembersResponse
	(*AddMemberRequest)(nil),             // 15: referral.AddMemberRequest
	(*AddMemberResponse)(nil),            // 16: referral.AddMemberResponse
	(*Referral)(nil),                     // 17: referral.Referral
	(*AddReferralRequest)(nil),           // 18: referral.AddReferralRequest
	(*AddReferralResponse)(nil),          // 19: referral.AddReferralResponse
	(*GetReferralsRequest)(nil),          // 20: referral.GetReferralsRequest
	(*GetReferralsResponse)(nil),         // 21: referral.GetReferralsResponse
}
var file_referral_referral_proto_depIdxs = []int32{
	0,  // 0: referral.ReferralLinkWrapper.referrallink:type_name -> referral.GenerateReferralLinkRequest
	3,  // 1: referral.UpdagteProgramResponse.program:type_name -> referral.Program
	3,  // 2: referral.GetProgramsResponse.programs:type_name -> referral.Program
	3,  // 3: referral.GetProgramResponse.program:type_name -> referral.Program
	12, // 4: referral.GetMembersResponse.members:type_name -> referral.Member
	17, // 5: referral.GetReferralsResponse.referrals:type_name -> referral.Referral
	8,  // 6: referral.referral_service.GetPrograms:input_type -> referral.GetProgramsRequest
	10, // 7: referral.referral_service.GetProgram:input_type -> referral.GetProgramRequest
	4,  // 8: referral.referral_service.AddProgram:input_type -> referral.AddProgramRequest
	6,  // 9: referral.referral_service.UpdateProgram:input_type -> referral.UpdateProgramRequest
	13, // 10: referral.referral_service.GetMembers:input_type -> referral.GetMembersRequest
	15, // 11: referral.referral_service.AddMember:input_type -> referral.AddMemberRequest
	20, // 12: referral.referral_service.GetReferrals:input_type -> referral.GetReferralsRequest
	18, // 13: referral.referral_service.AddReferral:input_type -> referral.AddReferralRequest
	9,  // 14: referral.referral_service.GetPrograms:output_type -> referral.GetProgramsResponse
	11, // 15: referral.referral_service.GetProgram:output_type -> referral.GetProgramResponse
	5,  // 16: referral.referral_service.AddProgram:output_type -> referral.AddProgramResponse
	7,  // 17: referral.referral_service.UpdateProgram:output_type -> referral.UpdagteProgramResponse
	14, // 18: referral.referral_service.GetMembers:output_type -> referral.GetMembersResponse
	16, // 19: referral.referral_service.AddMember:output_type -> referral.AddMemberResponse
	21, // 20: referral.referral_service.GetReferrals:output_type -> referral.GetReferralsResponse
	19, // 21: referral.referral_service.AddReferral:output_type -> referral.AddReferralResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_referral_referral_proto_init() }
func file_referral_referral_proto_init() {
	if File_referral_referral_proto != nil {
		return
	}
	file_referral_referral_proto_msgTypes[6].OneofWrappers = []any{}
	file_referral_referral_proto_msgTypes[8].OneofWrappers = []any{}
	file_referral_referral_proto_msgTypes[13].OneofWrappers = []any{}
	file_referral_referral_proto_msgTypes[15].OneofWrappers = []any{}
	file_referral_referral_proto_msgTypes[18].OneofWrappers = []any{}
	file_referral_referral_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_referral_referral_proto_rawDesc), len(file_referral_referral_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_referral_referral_proto_goTypes,
		DependencyIndexes: file_referral_referral_proto_depIdxs,
		MessageInfos:      file_referral_referral_proto_msgTypes,
	}.Build()
	File_referral_referral_proto = out.File
	file_referral_referral_proto_goTypes = nil
	file_referral_referral_proto_depIdxs = nil
}
